[package]
name = "extractor"
author.workspace = true
version.workspace = true
edition.workspace = true

[dependencies]
registry = { path = "./proc-macro/registry" }
thiserror.workspace = true
once_cell.workspace = true
regex.workspace = true
serde.workspace = true
scraper = "*"
